apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::516861151784:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-8V1nUKBYUIyQ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::516861151784:user/Shabu
      username: shabu
kind: ConfigMap
metadata:
  creationTimestamp:  "2026-01-02T10:29:55Z"
  name: aws-auth
  namespace: kube-system
  uid:  56ec7a63-37be-4711-904f-6a164774ba3e
